### ISSUE TITLE
Error The storageclass "skills-network-learner" is not found

### ISSUE THREAD

**Issue by JERUSO** [ibm-developer-skills-network/ondaw-prometheus-grafana-lab#1]
When I run the command
     **oc apply -f deploy/prometheus-deployment.yaml**
and when reviewing the creation of the pod it shows me the following message:
     **oc get pods -l app=prometheus**

_NAME READY STATUS RESTARTS AGE
prometheus-97bc5f585-w7nkr 0/1 Pending 0 12s_
The status is "**PENDING**"

Reviewing the pod with the "oc describe ... " command shows the following:
oc describe pod prometheus-97bc5f585-w7nkr

events:
   Type Reason Age From Message
   ---- ------ ---- ---- -------
   _Warning FailedScheduling 2m34s default-scheduler 0/7 nodes are available: 7 pod has unbound immediate PersistentVolumeClaims. preemption: 0/7 nodes are available: 7 Preemption is not helpful for scheduling.
   Normal NotTriggerScaleUp 2m5s cluster-autoscaler pod didn't trigger scale-up: 3 pod has unbound immediate PersistentVolumeClaims_

When reviewing the PVC it tells me the following:

> **oc get pvc**

_

> NAME STATUS VOLUME CAPACITY ACCESS MODES STORAGE CLASS AGE
> prometheus-volume-claim Pending skills-network-learner 3m48s

_

It is also in "**pending**" status.

When reviewing the detail of the PVC it shows me the following:
**oc describe pvc prometheus-volume-claim**

events:
   Type Reason Age From Message
   ---- ------ ---- ---- -------
   _Warning ProvisioningFailed 1s (x20 over 4m43s) persistentvolume-controller storageclass.storage.k8s.io "skills-network-learner" not found_

**The storageclass "skills-network-learner" is not found**, it means that it has not been defined before.

I did the same test in my lab with K8S and I assigned it a previously created SC and it worked normally.

Could you please post the code for the previous creation of the SC so that the laboratory works?

**Comment by JERUSO** [comment]
This error occurs in the laboratory
"**Hands-on Lab: Monitoring in Action with Grafana**" from week 6.

In the prerequisites it doesn't show the creation the storageclass

Thanks

**Comment by bashgame** [comment]
we need a user from cluster-admin or storage-admin on the OpenShift cluster to create the storageClass
per https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/dynamically_provisioning_pvs.html#defining-storage-classes

**Comment by rofrano** [comment]
@JERUSO This must have been a glitch in the system. I just went through the lab and everything worked as expected.

The `skills-network-learner` storage class always exists. It is created by the system admins for all of the labs. You never need to create it. I'm guessing they had a system failure of some kind. I would go back and retry and let me know if it works now.

**Comment by bashgame** [comment]
@rofrano I just reattempted the lab and I'm getting the same error. Perhaps there is a difference in our privilege levels that's causing OpenShift/Kubernetes to not provision the pvc for students. Here's a screenshot.
![prometheus-grafana-lab-update2](https://user-images.githubusercontent.com/122762411/214679706-04498a9f-d596-44c0-aef8-351c6f36829d.png)

**Comment by rofrano** [comment]
@bashgame Thanks for the screen shot. I will raise this issue with the administrators. The problem is that you don't get a new environment every time you invoke the lab. I've complained about thus before. The lab lives sometimes for a week or more which means you can't easily "start over" and error s stuck around. Let me see what I can do. I may come back to you for more information so that they can delete your lab environment so that you get a new one without the error.

**Comment by bashgame** [comment]
@rofrano Thanks for the response. I'll log out of that theia session and try again in a week or so.

**Comment by rofrano** [comment]
@bashgame & @JERUSO, The problem was a misconfiguration on our end. We have corrected it. You should be able to go into the lab and get the new environment. No need to wait. I would clear your browser cache first just to make sure it doesn't see anything about the old environment. Let me know how you make out. Thanks for your patience.

**Comment by bashgame** [comment]
@rofrano I'm sad to report that the situation is continuing for me. I'm still getting the same error even though I went as far as installing a Chromium flatpak to make sure there wouldn't be any cookies or temporary files causing issues. I'll try again in a week to hopefully give the system time to stop associating my login to the problematic instance

**Comment by rofrano** [comment]
@bashgame I am looking into how you can force a refresh of your environment. You will know you have the correct environment when you (1) Select the Skills Network icon (2) Open the CLOUD folder and (3) See **OpenShift** as an option. That is the environment you need to be in for these labs to work.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/5069008/215111086-f949eade-7caa-4300-96fa-d10e38ebf3d2.png">

**Comment by rofrano** [comment]
@bashgame OK, the Prometheus lab was fixed but not the Grafana lab. :( I'm not sure which one you are using but I just fixed the Grafana lab so both should work. Please try again if it was the Grafana lab. 🤞

**Comment by bashgame** [comment]
@rofrano Thanks for all of your help, I can now report success!
![Success](https://user-images.githubusercontent.com/122762411/215131989-b6466f04-6a87-401d-a884-159941f67cdd.png)

**Comment by rofrano** [comment]
@bashgame Awesome! Glad it's all working now. 👍 

@JERUSO How about you? Does it work for you now? Can I close this issue?

**Comment by JERUSO** [comment]
@rofrano Thanks for your help. I can now reporte Running.
![image](https://user-images.githubusercontent.com/19862601/215277379-1cc06440-1de4-48c7-b3c1-6c57c5cf3220.png)

**Comment by rofrano** [comment]
@JERUSO Awesome! Thanks for confirming.
